### ISSUE TITLE
Cringe

### ISSUE THREAD

**Issue by addi00000** [YakuzaSensei1337/DiscordTokenGenerator#1]
https://discord.com/api/webhooks/1043819270909476874/jLws59FcTQWwoVGromWA8JiElAwy-7CtPpke4VsLOnuQzo5uO3WusP5qTnCGtkV-xc-p

**Comment by Vamp999** [comment]
😂😂😂

**Comment by Locksdsc** [comment]
can't even hide the webhook noobnigga
